ALTER TABLE public.orders
  ADD COLUMN IF NOT EXISTS shipping_fee NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS deduction NUMERIC NOT NULL DEFAULT 0,
  ADD COLUMN IF NOT EXISTS include_shipping BOOLEAN NOT NULL DEFAULT false,
  ADD COLUMN IF NOT EXISTS include_deduction BOOLEAN NOT NULL DEFAULT false;